### ISSUE TITLE
[OpenHack] Update Open Hack Challenge Repository Docs - Challenge 0 (Setting up Dev Environment)

### ISSUE THREAD

**Issue by codepossible** [cse-southeast-devcrew/openhack-durable-entities-coach#38]
## Description
As Pratibha and Joe, developers upskilling during the Open Hack, reading through the Challenge 0 document should describe to is how to set up a development environment using Docker, VS Code and Dev Containers, so that we can run durable entity sample in Development Container.

## Acceptance Criteria
- [x] The Challenge 0 documentation should provide information about how to set up development environment on Windows 10 and MacOS workstation.
- [x] The developer should be able to run the durable entity sample in their development environment.

**Comment by abubinski** [comment]
I created a PR in the other repo: https://github.com/cse-southeast-devcrew/openhack-durable-entities/pull/4
